### ISSUE TITLE
Handler Error

### ISSUE THREAD

**Issue by xTridentSecurityx** [IPQualityScore/PythonIPQSDBReader#2]
Hey im getting this error from your package

**Invalid or non existant file name specified. Please check the file and try again
Exception ignored in: <function DBReader.__del__ at 0x7f11d39ad8b0>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/IPQualityScore/DBReader.py", line 288, in __del__
    if self.handler:
AttributeError: 'DBReader' object has no attribute 'handler**

can yall fix this so i can start using it?

**Comment by Kuldran** [comment]
From the message, it would appear you did not specify the file to use or its perms are set incorrectly. if you don't mind what file are you trying open?

As an example here is a test a ran here where I put the wrong file to open.

Traceback (most recent call last):
  File "/dev/testing/PythonDBReader/example.py", line 3, in <module>
    u = DBReader("IPQualityScore-IP-Reputation-Database-IPv63.ipqs").Fetch("2001:4860:4860::8844")
  File "/dev/testing/PythonDBReader/IPQualityScore/DBReader.py", line 29, in __init__
    raise FileReaderException('Invalid or non existant file name specified. Please check the file and try again')
IPQualityScore.Exceptions.FileReaderException: Invalid or non existant file name specified. Please check the file and try again
Exception ignored in: <function DBReader.__del__ at 0x7fc6f42fb820>
Traceback (most recent call last):
  File "/dev/testing/PythonDBReader/IPQualityScore/DBReader.py", line 288, in __del__
    if self.handler:
AttributeError: 'DBReader' object has no attribute 'handler'

**Comment by xTridentSecurityx** [comment]
got it thank you!
